project_name: pr-files
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- main: main.go
  binary: pr-files
  goarch:
    - amd64
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
